package roman.com.footballscorekeeper;

import android.databinding.DataBindingUtil;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;

import roman.com.footballscorekeeper.databinding.ActivityMainBinding;

/**
 * Main and only activity in this project
 */
public class MainActivity extends AppCompatActivity {

    //default value for all the score and foul counters
    private final static String DEFAULT_SCORE = "0";

       /*
         * this project had many buttons - so I chose to use the databinding library to minimize boilerplate code
         * hopefully it's okay :)
         */

    //autogenerated class by the databinding library
    private ActivityMainBinding mBinding;

    /**
     * this is where we connect the xml to java and initialize things
     * @param savedInstanceState
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        //get the binding object for activity_main.xml
        mBinding = DataBindingUtil.setContentView(this,R.layout.activity_main);
    }

    /**
     * click listener for the increment score button for Team A
     * @param view
     */
    public void onClickIncrementScoreTeamA(View view) {
        int score = Integer.valueOf(mBinding.textviewTeamAScore.getText().toString());
        score++;
        mBinding.textviewTeamAScore.setText(String.valueOf(score));
    }

    /**
     * click listener for the increment fouls button for Team A
     * @param view
     */
    public void onClickIncrementFoulsTeamA(View view) {
        int foulNum = Integer.valueOf(mBinding.textviewTeamAFouls.getText().toString());
        foulNum++;
        mBinding.textviewTeamAFouls.setText(String.valueOf(foulNum));
    }

    /**
     * click listener for the increment score button for Team B
     * @param view
     */
    public void onClickIncrementScoreTeamB(View view) {
        int score = Integer.valueOf(mBinding.textviewTeamBScore.getText().toString());
        score++;
        mBinding.textviewTeamBScore.setText(String.valueOf(score));
    }


    /**
     * click listener for the increment fouls button for Team B
     * @param view
     */
    public void onClickIncrementFoulsTeamB(View view) {
        int foulNum = Integer.valueOf(mBinding.textviewTeamBFouls.getText().toString());
        foulNum++;
        mBinding.textviewTeamBFouls.setText(String.valueOf(foulNum));
    }

    /**
     *  click listener for the reset button
     * @param view
     */
    public void onClickReset(View view){
        mBinding.textviewTeamAScore.setText(DEFAULT_SCORE);
        mBinding.textviewTeamAFouls.setText(DEFAULT_SCORE);
        mBinding.textviewTeamBScore.setText(DEFAULT_SCORE);
        mBinding.textviewTeamBFouls.setText(DEFAULT_SCORE);
    }


}
